Renzo Salazar Cueva

Medium Sources: 

https://medium.com/learning-sql/finding-gaps-with-sql-4f62982f797d

https://medium.com/@manutej/mastering-sql-window-functions-guide-e6dc17eb1995

In [10]:
import pyodbc
pyodbc.drivers()

['SQL Server',
 'ODBC Driver 17 for SQL Server',
 'ODBC Driver 18 for SQL Server',
 'Microsoft Access Driver (*.mdb, *.accdb)',
 'Microsoft Excel Driver (*.xls, *.xlsx, *.xlsm, *.xlsb)',
 'Microsoft Access Text Driver (*.txt, *.csv)',
 'Microsoft Access dBASE Driver (*.dbf, *.ndx, *.mdx)']

In [23]:
from urllib.parse import quote_plus
import sqlalchemy as sa
import pandas as pd

pd.set_option('display.max_colwidth', None)
pd.set_option("display.max_rows", None)


password = quote_plus("PH@123456789")
CONN_URL = (
    f"mssql+pyodbc://sa:{password}@localhost:13001/Northwinds2022TSQLV7"
    "?driver=ODBC+Driver+18+for+SQL+Server&TrustServerCertificate=yes"
)

engine = sa.create_engine(CONN_URL)

with engine.connect() as conn:
    print("Connected to:", conn.exec_driver_sql("SELECT DB_NAME()").scalar())

def run(query: str) -> pd.DataFrame:
    """Execute a SQL query and return the results as a DataFrame."""
    with engine.connect() as conn:
        return pd.read_sql_query(query, conn)
    
def show(df, n=20):
    display(df.iloc[:n])

Connected to: Northwinds2022TSQLV7

Query 1

This assigns a sequential number to each customer's orders, showing you 
their first order, second order, third order, and so on. Marketing teams 
use this to identify repeat customers with loyalty programs, or 
flag first-time buyers to ensure they become repeat customers.

In [24]:
df = run("""
SELECT CustomerId,OrderId, OrderDate, 
    ROW_NUMBER() OVER (PARTITION BY CustomerId ORDER BY OrderDate) AS OrderNumber
FROM Sales.[Order];
""")

show(df)

    CustomerId  OrderId   OrderDate  OrderNumber
0            1    10643  2015-08-25            1
1            1    10692  2015-10-03            2
2            1    10702  2015-10-13            3
3            1    10835  2016-01-15            4
4            1    10952  2016-03-16            5
5            1    11011  2016-04-09            6
6            2    10308  2014-09-18            1
7            2    10625  2015-08-08            2
8            2    10759  2015-11-28            3
9            2    10926  2016-03-04            4
10           3    10365  2014-11-27            1
11           3    10507  2015-04-15            2
12           3    10535  2015-05-13            3
13           3    10573  2015-06-19            4
14           3    10677  2015-09-22            5
15           3    10682  2015-09-25            6
16           3    10856  2016-01-28            7
17           4    10355  2014-11-15            1
18           4    10383  2014-12-16            2
19           4    10453  2015-02-21            3

Query 2
This tracks each employee's cumulative shipping costs separately, helping 
managers identify which sales representatives generate the most freight 
expenses over time. It's valuable for performance reviews and territory 
planning, as there might be opportunities to negotiate better shipping rates 
for certain regions.

In [25]:
df = run("""
SELECT EmployeeId,OrderId, OrderDate, Freight,
    SUM(Freight) OVER (PARTITION BY EmployeeId ORDER BY OrderDate) AS RunningTotalPerEmployee
FROM Sales.[Order];
""")

show(df)

    EmployeeId  OrderId   OrderDate  Freight  RunningTotalPerEmployee
0            1    10258  2014-07-17   140.51                   140.51
1            1    10270  2014-08-01   136.54                   277.05
2            1    10275  2014-08-07    26.93                   303.98
3            1    10285  2014-08-20    76.83                   380.81
4            1    10292  2014-08-28     1.35                   382.16
5            1    10293  2014-08-29    21.18                   403.34
6            1    10304  2014-09-12    63.79                   467.13
7            1    10306  2014-09-16     7.56                   474.69
8            1    10311  2014-09-20    24.69                   499.38
9            1    10314  2014-09-25    74.16                   573.54
10           1    10316  2014-09-27   150.15                   723.69
11           1    10325  2014-10-09    64.86                   788.55
12           1    10340  2014-10-29   166.31                   954.86
13           1    10351  2014-11-11   162.33                  1117.19
14           1    10357  2014-11-19    34.88                  1152.07
15           1    10361  2014-11-22   183.17                  1335.24
16           1    10364  2014-11-26    71.97                  1407.21
17           1    10371  2014-12-03     0.45                  1407.66
18           1    10374  2014-12-05     3.94                  1411.60
19           1    10376  2014-12-09    20.39                  1454.20

Query 3
This ranks all orders from most to least expensive in terms of shipping 
costs, helping operations teams identify shipments that need 
investigation. If you see unusually high freight costs, it might indicate 
errors in packaging, or even wrong carrier selection.

In [26]:
df = run("""
SELECT OrderId, Freight,
    RANK() OVER (ORDER BY Freight DESC) AS FreightRank
FROM Sales.[Order];
""")


show(df)

    OrderId  Freight  FreightRank
0     10540  1007.64            1
1     10372   890.78            2
2     11030   830.75            3
3     10691   810.05            4
4     10514   789.95            5
5     11017   754.26            6
6     10816   719.78            7
7     10479   708.95            8
8     10983   657.54            9
9     11032   606.19           10
10    10897   603.54           11
11    10912   580.91           12
12    10612   544.08           13
13    10847   487.57           14
14    10634   487.38           15
15    10633   477.90           16
16    10430   458.78           17
17    10841   424.30           18
18    10836   411.88           19
19    10941   400.81           20

Query 4
This creates a price ranking for a product catalog, showing which items 
are premium, mid range, or budget friendly without gaps in ranking numbers. 
Product managers use this for pricing strategy and ensuring your product mix 
covers different customer segments from casual buyers to premium customers.

In [27]:
df = run("""
SELECT ProductId, ProductName, UnitPrice,
    DENSE_RANK() OVER (ORDER BY UnitPrice DESC) AS PriceRank
FROM Production.Product;
""")

show(df)

    ProductId                ProductName  UnitPrice  PriceRank
0          38              Product QDOMO     263.50          1
1          29              Product VJXYN     123.79          2
2           9              Product AOZBW      97.00          3
3          20              Product QHFFP      81.00          4
4          18              Product CKEDC      62.50          5
5          59              Product UKXRI      55.00          6
6          51              Product APITJ      53.00          7
7          62              Product WUXYK      49.30          8
8          43  Product ZZZHumanResources      46.00          9
9          28              Product OFBNT      45.60         10
10         27              Product SMIOH      43.90         11
11         63              Product ICKNK      43.90         11
12          8              Product WVJFP      40.00         12
13         17              Product BLCAX      39.00         13
14         12              Product OSFNS      38.00         14
15         56              Product VKCMF      38.00         14
16         69              Product COAXA      36.00         15
17         72              Product GEEOO      34.80         16
18         60              Product WHBYK      34.00         17
19         64              Product HCQDE      33.25         18

Query 5
This shows each order's shipping cost alongside the previous order's cost, 
making it easy to spot any sudden changes in freight expenses. Logistics teams 
can use this to detect anomalies like carrier rate increases or data entry errors
that need correction before invoices are finalized and the company ends up overpaying
for shipping.

In [28]:
df = run("""
SELECT OrderId, OrderDate, Freight,
    LAG(Freight) OVER (ORDER BY OrderDate) AS PreviousFreight
FROM Sales.[Order];
""")

show(df)

    OrderId   OrderDate  Freight  PreviousFreight
0     10248  2014-07-04    32.38              NaN
1     10249  2014-07-05    11.61            32.38
2     10250  2014-07-08    65.83            11.61
3     10251  2014-07-08    41.34            65.83
4     10252  2014-07-09    51.30            41.34
5     10253  2014-07-10    58.17            51.30
6     10254  2014-07-11    22.98            58.17
7     10255  2014-07-12   148.33            22.98
8     10256  2014-07-15    13.97           148.33
9     10257  2014-07-16    81.91            13.97
10    10258  2014-07-17   140.51            81.91
11    10259  2014-07-18     3.25           140.51
12    10260  2014-07-19    55.09             3.25
13    10261  2014-07-19     3.05            55.09
14    10262  2014-07-22    48.29             3.05
15    10263  2014-07-23   146.06            48.29
16    10264  2014-07-24     3.67           146.06
17    10265  2014-07-25    55.28             3.67
18    10266  2014-07-26    25.73            55.28
19    10267  2014-07-29   208.58            25.73

Query 6

This displays each order with the dates of the employee's previous and next 
orders, revealing their sales activity patterns. Sales managers can use 
this to identify slow periods where a sales person might need coaching, 
or find consistent performers who consistently keep orders moving.

In [29]:
df = run("""
SELECT EmployeeId,OrderId, OrderDate,
    LAG(OrderDate) OVER (PARTITION BY EmployeeId ORDER BY OrderDate) AS PrevOrderDate,
    LEAD(OrderDate) OVER (PARTITION BY EmployeeId ORDER BY OrderDate) AS NextOrderDate
FROM Sales.[Order];
""")

show(df)

    EmployeeId  OrderId   OrderDate PrevOrderDate NextOrderDate
0            1    10258  2014-07-17          None    2014-08-01
1            1    10270  2014-08-01    2014-07-17    2014-08-07
2            1    10275  2014-08-07    2014-08-01    2014-08-20
3            1    10285  2014-08-20    2014-08-07    2014-08-28
4            1    10292  2014-08-28    2014-08-20    2014-08-29
5            1    10293  2014-08-29    2014-08-28    2014-09-12
6            1    10304  2014-09-12    2014-08-29    2014-09-16
7            1    10306  2014-09-16    2014-09-12    2014-09-20
8            1    10311  2014-09-20    2014-09-16    2014-09-25
9            1    10314  2014-09-25    2014-09-20    2014-09-27
10           1    10316  2014-09-27    2014-09-25    2014-10-09
11           1    10325  2014-10-09    2014-09-27    2014-10-29
12           1    10340  2014-10-29    2014-10-09    2014-11-11
13           1    10351  2014-11-11    2014-10-29    2014-11-19
14           1    10357  2014-11-19    2014-11-11    2014-11-22
15           1    10361  2014-11-22    2014-11-19    2014-11-26
16           1    10364  2014-11-26    2014-11-22    2014-12-03
17           1    10371  2014-12-03    2014-11-26    2014-12-05
18           1    10374  2014-12-05    2014-12-03    2014-12-09
19           1    10376  2014-12-09    2014-12-05    2014-12-09

Query 7
This displays when the first and last order date in the dataset, . 
Sales Managers can use this to identify inactive employees who might 
need intervention, and recognize long term performers whose experience 
who can mentor newer team members.

In [ ]:
df = run("""
SELECT DISTINCT
    EmployeeId,
    FIRST_VALUE(OrderDate) OVER (PARTITION BY EmployeeId ORDER BY OrderDate) AS FirstOrderDate,
    LAST_VALUE(OrderDate) OVER (PARTITION BY EmployeeId ORDER BY OrderDate 
        ROWS BETWEEN UNBOUNDED PRECEDING AND UNBOUNDED FOLLOWING) AS LastOrderDate
FROM Sales.[Order];
""")

show(df)

   EmployeeId FirstOrderDate LastOrderDate
0           1     2014-07-17    2016-05-06
1           2     2014-07-25    2016-05-05
2           3     2014-07-08    2016-04-30
3           4     2014-07-08    2016-05-06
4           5     2014-07-04    2016-04-22

Query 8
This query shows how much each freight charge contributes to the employee’s 
overall shipping total. It highlights orders that are unusually expensive compared
to their normal pattern. Sales teams can use this to review and spot potential cost issues, 
and understand how each employee handles freight across their orders.

In [31]:
df = run("""
SELECT EmployeeId,OrderId, Freight,
    100.0 * Freight / SUM(Freight) OVER (PARTITION BY EmployeeId) AS PercentageOfEmployeeTotal
FROM Sales.[Order];
""")

show(df)

    EmployeeId  OrderId  Freight  PercentageOfEmployeeTotal
0            1    10258   140.51                   1.590084
1            1    10270   136.54                   1.545157
2            1    10275    26.93                   0.304754
3            1    10285    76.83                   0.869448
4            1    10292     1.35                   0.015277
5            1    10293    21.18                   0.239684
6            1    10304    63.79                   0.721881
7            1    10306     7.56                   0.085553
8            1    10311    24.69                   0.279405
9            1    10314    74.16                   0.839233
10           1    10316   150.15                   1.699175
11           1    10325    64.86                   0.733989
12           1    10340   166.31                   1.882050
13           1    10351   162.33                   1.837010
14           1    10357    34.88                   0.394720
15           1    10361   183.17                   2.072847
16           1    10364    71.97                   0.814450
17           1    10371     0.45                   0.005092
18           1    10374     3.94                   0.044587
19           1    10376    20.39                   0.230744

Query 9
This keeps a running count of how many orders each customer has placed up to 
any point in time, creating a simple timeline of their purchase activity. Sales or
management teams can use this data to monitor customer engagement, purchase behaviour
and if their purchase actvity slows down.

In [32]:
df = run("""
SELECT CustomerId,OrderId, OrderDate,
    COUNT(*) OVER (PARTITION BY CustomerId ORDER BY OrderDate) AS CumulativeOrderCount
FROM Sales.[Order];
""")

show(df)

    CustomerId  OrderId   OrderDate  CumulativeOrderCount
0            1    10643  2015-08-25                     1
1            1    10692  2015-10-03                     2
2            1    10702  2015-10-13                     3
3            1    10835  2016-01-15                     4
4            1    10952  2016-03-16                     5
5            1    11011  2016-04-09                     6
6            2    10308  2014-09-18                     1
7            2    10625  2015-08-08                     2
8            2    10759  2015-11-28                     3
9            2    10926  2016-03-04                     4
10           3    10365  2014-11-27                     1
11           3    10507  2015-04-15                     2
12           3    10535  2015-05-13                     3
13           3    10573  2015-06-19                     4
14           3    10677  2015-09-22                     5
15           3    10682  2015-09-25                     6
16           3    10856  2016-01-28                     7
17           4    10355  2014-11-15                     1
18           4    10383  2014-12-16                     2
19           4    10453  2015-02-21                     3

Query 10
This query tracks the highest freight cost each employee has handled
up to each order date. It builds a history of their exposure to large
or complex shipments over time. It reveals patterns in shipping costs 
across employees and highlights moments where freight charges stand out
from their usual activity.

In [ ]:
df = run("""
SELECT EmployeeId,OrderId, OrderDate, Freight,
    MAX(Freight) OVER (PARTITION BY EmployeeId ORDER BY OrderDate) AS MaxFreightSoFar
FROM Sales.[Order];
""")

show(df)

   EmployeeId  OrderId   OrderDate  Freight  MaxFreightSoFar
0           1    10258  2014-07-17   140.51           140.51
1           1    10270  2014-08-01   136.54           140.51
2           1    10275  2014-08-07    26.93           140.51
3           1    10285  2014-08-20    76.83           140.51
4           1    10292  2014-08-28     1.35           140.51